# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e588a072dbbc6473eb90830fa3b59fe203ab7f78ae81d156d5a39ea91f6a1f9afc4c91362106bbc1fb0f727e2d7accc904511c3f2748e2953a5e9d5837118eb

test:
  secret_key_base: 3a2a641d5d5b3f13f641751abb8310b91706d5bbadc6cf2bd4c5ed5f4e4ed7c4f3d0a2f6a9f6f888043fb6a14b1248b677b148f29a01e8a7cdf33e8d5ae62bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
